// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvqambsuvlqauledrndt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cWFtYnN1dmxxYXVsZWRybmR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MjAzNTAsImV4cCI6MjA2MzE5NjM1MH0.AapcxUyxCbh0GOuJvuGh5uSGuo5_7EHqH2Mx6Jc8y88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);